(defun operacao(op x y)
  (if (string= op "+")
    (+ x y)
    (if (string= op "-")
      (- x y)
      (if (string= op "*")
        (* x y)
        (/ x y)
      )
    )
  )
)

(defun main()
  (setq operador (read))
  (setq x (read))
  (setq y (read))
  (write-line (write-to-string (operacao operador x y)))
)

(main)